# Configuração de Build para o Netlify
# Este arquivo informa ao Netlify como construir e fazer o deploy do seu site.

[build]
  # Comando de build: Comando que o Netlify usará para construir seu site.
  # Ele executará o script "build" do `package.json` da raiz, que por sua vez
  # chama o build do frontend.
  command = "npm run build"
  
  # Diretório de publicação: A pasta que contém os arquivos finais do site (gerada pelo comando de build).
  # O Netlify publicará o conteúdo de `frontend/dist`.
  publish = "frontend/dist"

  # Diretório das Funções: Informa ao Netlify onde encontrar as funções serverless.
  # O Netlify irá procurar por `netlify/functions/api.js`.
  functions = "netlify/functions"

[build.environment]
  # Garante que o Netlify use uma versão do Node.js compatível com suas dependências.
  NODE_VERSION = "18"
  # Define a URL da API para o build de produção. O prefixo VITE_ é necessário
  # para que o Vite exponha essa variável para o código do frontend.
  VITE_API_URL = "/api"

# Redirecionamento para a API
# Todas as chamadas para /api/* serão redirecionadas para nossa função serverless.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200