# Configuração de Build para o Netlify
# Este arquivo informa ao Netlify como construir e fazer o deploy do seu site.

[build]
  # Diretório base: O Netlify executará os comandos a partir desta pasta.
  base = "frontend"

  # Comando de build: Comando que o Netlify usará para construir seu site.
  # Ele executará o script "build" do arquivo `frontend/package.json`.
  command = "npm run build"

  # Diretório de publicação: A pasta que contém os arquivos finais do site (gerada pelo comando de build).
  # O Netlify publicará o conteúdo de `frontend/dist`.
  publish = "dist"

[build.environment]
  # Garante que o Netlify use uma versão do Node.js compatível com suas dependências.
  NODE_VERSION = "18"

# Redirecionamento para a API
# Todas as chamadas para /api/* serão redirecionadas para nossa função serverless.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200